Update to latest bindings (#13)

diff --git a/mlir/support/cmake-helper b/mlir/support/cmake-helper
--- a/mlir/support/cmake-helper
+++ b/mlir/support/cmake-helper
@@ -14,10 +14,20 @@ case "$1" in
     shift 1 # Remove "configure" from the arguments
 
     VSCODE_SETTINGS_FILE=${VSCODE_SETTINGS_FILE:-$PROJECT_ROOT/.devcontainer/default/VSCode/settings.json}
+    if ! sed 's@//.*@@' < "$VSCODE_SETTINGS_FILE" | jq . > /dev/null; then
+      echo "Error: $VSCODE_SETTINGS_FILE is not a valid JSON file."
+      exit 1
+    fi
 
-    # If specified, sets the CMAKE_{C,CXX}_COMPILER variables as specified in the CMake Tools kits file. 
+    # If specified, sets the CMAKE_{C,CXX}_COMPILER variables as specified in the CMake Tools kits file.
     CMAKE_TOOLS_KITS_FILE=${CMAKE_TOOLS_KITS_FILE:-}
     CMAKE_TOOLS_KITS_FILE_INDEX=${CMAKE_TOOLS_KITS_FILE_INDEX:-0}
+    if [[ -n "$CMAKE_TOOLS_KITS_FILE" ]]; then
+      if ! jq . < "$CMAKE_TOOLS_KITS_FILE" > /dev/null; then
+        echo "Error: $CMAKE_TOOLS_KITS_FILE is not a valid JSON file."
+        exit 1
+      fi
+    fi
     
     CMAKE_ARGS=$(
       set -e
@@ -48,8 +58,15 @@ case "$1" in
     shift 1 # Remove "build" or "test" from the arguments
 
     if [[ $# -eq 0 ]]; then
-      readarray -t TARGETS < <(jq -r "[.tasks[] | select(.group | .kind == \"$TASK_KIND\" and .isDefault)][0] | .targets | join(\"\n\")" < "$PROJECT_ROOT/.devcontainer/default/VSCode/tasks.json")
-    else 
+      TASKS_JSON=".devcontainer/default/VSCode/tasks.json"
+      if ! jq . < "$PROJECT_ROOT/$TASKS_JSON" > /dev/null; then
+        echo "Error: $TASKS_JSON is not a valid JSON file."
+        exit 1
+      fi
+      while IFS="=" read -r next; do
+        TARGETS+=("$next")
+      done < <(jq -r "[.tasks[] | select(.group | .kind == \"$TASK_KIND\" and .isDefault)][0] | .targets | join(\"\n\")" < "$PROJECT_ROOT/.devcontainer/default/VSCode/tasks.json")
+    else
       TARGETS=("$@")
     fi
 
